language: r
warnings_are_errors: false
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - hadley/testthat
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

